import { BreadCrumb } from "@/components/BreadCrumb";
import { changeTitle } from "@/globals";

function Docs() {
  changeTitle("Introduction | Beauty/ui");
  return (
    <div>
      <BreadCrumb titles={["Docs", "Introduction"]} />
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
      <h1>Docs</h1>
    </div>
  );
}

export default Docs;
